# =============================================
# Configuración del servidor
# =============================================
server:
  port: 8083                  # Puerto del servicio
  servlet:
    context-path: /credit     # Context path base (opcional)

spring:
  application:
    name: credit-service      # Nombre de la aplicación para registro y Eureka si se usa
  data:
    mongodb:
      uri: mongodb://mongo:27017/bank_db
      reactive:
        auto-index-creation: true
  main:
    allow-bean-definition-overriding: true
  devtools:
    restart:
      enabled: true
  redis:
    host: ${REDIS_HOST:redis}  # Host de Redis (variable de entorno REDIS_HOST, por defecto 'redis')
    port: ${REDIS_PORT:6379}   # Puerto de Redis (variable de entorno REDIS_PORT, por defecto 6379)

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.bank.credit: DEBUG   # Nivel de log para tu paquete

kafka:
  bootstrap-servers: kafka:9092

schema:
  registry:
    url: http://schema-registry:8081

