# =============================================
# Configuración del servidor
# =============================================
server:
  port: 8084

spring:
  application:
    name: transaction-service
  config:
    import: "optional:configserver:"
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://mongo-bank:27017/transaction_db}
      auto-index-creation: true
  main:
    allow-bean-definition-overriding: true
  devtools:
    restart:
      enabled: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka-1:9092}

# =============================================
# Logging
# =============================================
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.bank.transaction_service: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "health,info,env"
  endpoint:
    health:
      show-details: always
