server:
  port: 8084

spring:
  application:
    name: transaction-service

  config:
    import: "optional:configserver:"

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://mongo-bank:27017/transaction_db}
      auto-index-creation: true

  main:
    allow-bean-definition-overriding: true

  devtools:
    restart:
      enabled: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.bank.transaction_service: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "health,info,env"
  endpoint:
    health:
      show-details: always

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

# ---------------------------------------------------------
# 🔥 RESILIENCE4J
# ---------------------------------------------------------
resilience4j:
  circuitbreaker:
    instances:
      accountServiceCircuitBreaker:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

  timelimiter:
    instances:
      accountServiceCircuitBreaker:
        timeout-duration: 3s

  retry:
    instances:
      accountServiceRetry:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - java.io.IOException
          - org.springframework.web.reactive.function.client.WebClientRequestException

  bulkhead:
    instances:
      accountServiceBulkhead:
        max-concurrent-calls: 10
        max-wait-duration: 2s
