server:
  port: 8090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      actuator:
        enabled: true        # ? CAMBIO: habilita /actuator/gateway/routes

    httpclient:
      connect-timeout: 3000
      response-timeout: 5s

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

redis:
  host: redis
  port: 6379

management:
  endpoints:
    web:
      exposure:
        include: "*"          # ? expone todos los endpoints Actuator
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: true           # ? CAMBIO: habilita healthcheck real de Redis
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

resilience4j:
  retry:
    instances:
      redisRetry:
        max-attempts: 5
        wait-duration: 2s
        retry-exceptions:
          - org.springframework.data.redis.RedisConnectionFailureException

