server:
  port: 8082

spring:
  application:
    name: account-service

  data:
    mongodb:
      uri: mongodb://mongo-bank:27017/account_db

  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

  main:
    allow-bean-definition-overriding: true

  # 🔥 ZIPKIN + BRAVE (Micrometer Tracing)
  sleuth:
    sampler:
      probability: 1.0

  zipkin:
    base-url: http://zipkin:9411

# ---------------------------------------------------------
# 🔥 RESILIENCE4J
# ---------------------------------------------------------
resilience4j:
  circuitbreaker:
    instances:
      customerServiceCircuitBreaker:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

  timelimiter:
    instances:
      customerServiceCircuitBreaker:
        timeout-duration: 3s

  retry:
    instances:
      customerServiceRetry:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - java.io.IOException
          - org.springframework.web.reactive.function.client.WebClientRequestException

  bulkhead:
    instances:
      customerServiceBulkhead:
        max-concurrent-calls: 10
        max-wait-duration: 2s

# ---------------------------------------------------------
# 🔥 EUREKA
# ---------------------------------------------------------
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    com.bank.account_service: DEBUG

schema:
  registry:
    url: http://schema-registry:8081

management:
  endpoints:
    web:
      exposure:
        include: "health,info,env"
  endpoint:
    health:
      show-details: always
